name: AWS Lambda Deploy
author: Luke Ivie <luke.ivie@oforce.com>
description: Deploys an AWS Lambda

branding:
  icon: cloud
  color: orange

runs:
  using: "node12"
  main: "dist/index.js"

inputs:
  function-name:
    description: The name of the Lambda function
    required: true

  zip-package:
    description: ZIP package of Lambda and dependencies

  aws-access-key-id:
    description: AWS access key

  aws-secret-access-key:
    description: AWS secret key

  aws-region:
    description: AWS region
    default: us-west-1

  aws-session-token:
    description: AWS session token

  aws-profile:
    description: AWS profile

  aws-role:
    description: AWS role
